version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py loaddata airport_service_data.json &&
              python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
